version: "3.8"

services:
  db_migrations:
    build: "."
    command: [ "sh", "-c", "poetry run alembic upgrade head" ]
    environment:
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
    depends_on:
      - database
    volumes:
      - ./:/app

  backend:
    build: "."
    env_file: .env
    depends_on:
      - database
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    restart: always

  database:
    env_file: .env
    image: postgres:14.2
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
