"""added order/address relationship on tables

Revision ID: 58048d3d2d79
Revises: fc4f42acbba9
Create Date: 2023-06-15 16:19:54.353157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "58048d3d2d79"
down_revision = "fc4f42acbba9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("address_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        "orders_addresses_fk",
        "orders",
        "addresses",
        ["address_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("orders_addresses_fk", "orders", type_="foreignkey")
    op.drop_column("orders", "address_id")
    # ### end Alembic commands ###
