"""updated cascade on user-adress relationship

Revision ID: 5b30e44af13c
Revises: 8c82502eecf6
Create Date: 2023-06-14 13:25:38.442384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5b30e44af13c"
down_revision = "8c82502eecf6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("addresses_user_id_fkey", "addresses", type_="foreignkey")
    op.create_foreign_key(
        "addresses_user_id_fkey",
        "addresses",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("addresses_user_id_fkey", "addresses", type_="foreignkey")
    op.create_foreign_key(
        "addresses_user_id_fkey", "addresses", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
