"""added product_price field to order_item table

Revision ID: bb5652422430
Revises: db927e2f63ab
Create Date: 2023-06-15 09:19:05.337387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bb5652422430"
down_revision = "db927e2f63ab"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_items",
        sa.Column("product_price", sa.Numeric(precision=6, scale=2), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_items", "product_price")
    # ### end Alembic commands ###
